a=[[
ASSIGNMENT
    EXPCHAIN
        IDENTIFIER(a)
    ASSIGN(=)
    HEX(0x123)
ASSIGNMENT
    EXPCHAIN
        IDENTIFIER(a)
    ASSIGN(=)
    PARENTHESIS
        OPENBRACKET(()
        PARENTHESIS
            OPENBRACKET(()
            PARENTHESIS
                OPENBRACKET(()
                PARENTHESIS
                    OPENBRACKET(()
                    OPERATORCHAIN
                        NUMBER(1)
                        BINARY_OP(+)
                        NUMBER(2)
                    CLOSEBRACKET())
                CLOSEBRACKET())
            CLOSEBRACKET())
        CLOSEBRACKET())
ASSIGNMENT
    EXPCHAIN
        IDENTIFIER(d)
    ASSIGN(=)
    OPERATORCHAIN
        NUMBER(1)
        BINARY_OP(+)
        NUMBER(2)
        BINARY_OP(+)
        NUMBER(3)
        BINARY_OP(+)
        MIXED_OP(-)
        NUMBER(4)
EXPCHAIN
    IDENTIFIER(require)
    FUNCTIONCALL
        OPENBRACKET(()
        STRING("LifeBoatAPI")
        CLOSEBRACKET())
ASSIGNMENT
    EXPCHAIN
        IDENTIFIER(color_Highlight)
    ASSIGN(=)
    EXPCHAIN
        IDENTIFIER(LifeBoatAPI)
        DOTACCESS(.)
        IDENTIFIER(LBColorRGBA)
        COLONACCESS(:)
        IDENTIFIER(lbcolorrgba_newGammaCorrected)
        FUNCTIONCALL
            OPENBRACKET(()
            NUMBER(230)
            COMMA(,)
            NUMBER(230)
            COMMA(,)
            NUMBER(230)
            CLOSEBRACKET())
ASSIGNMENT
    EXPCHAIN
        IDENTIFIER(color_Inactive)
    ASSIGN(=)
    EXPCHAIN
        IDENTIFIER(LifeBoatAPI)
        DOTACCESS(.)
        IDENTIFIER(LBColorRGBA)
        COLONACCESS(:)
        IDENTIFIER(lbcolorrgba_newGammaCorrected)
        FUNCTIONCALL
            OPENBRACKET(()
            NUMBER(100)
            COMMA(,)
            NUMBER(100)
            COMMA(,)
            NUMBER(100)
            CLOSEBRACKET())
ASSIGNMENT
    EXPCHAIN
        IDENTIFIER(color_Active)
    ASSIGN(=)
    EXPCHAIN
        IDENTIFIER(LifeBoatAPI)
        DOTACCESS(.)
        IDENTIFIER(LBColorRGBA)
        COLONACCESS(:)
        IDENTIFIER(lbcolorrgba_newGammaCorrected)
        FUNCTIONCALL
            OPENBRACKET(()
            NUMBER(230)
            COMMA(,)
            NUMBER(150)
            COMMA(,)
            NUMBER(0)
            CLOSEBRACKET())
ASSIGNMENT
    EXPCHAIN
        IDENTIFIER(myButton)
    ASSIGN(=)
    EXPCHAIN
        IDENTIFIER(LifeBoatAPI)
        DOTACCESS(.)
        IDENTIFIER(LBTouchScreen)
        COLONACCESS(:)
        IDENTIFIER(lbtouchscreen_newStyledButton)
        FUNCTIONCALL
            OPENBRACKET(()
            NUMBER(0)
            COMMA(,)
            NUMBER(1)
            COMMA(,)
            NUMBER(31)
            COMMA(,)
            NUMBER(9)
            COMMA(,)
            STRING("Toggle")
            COMMA(,)
            EXPCHAIN
                IDENTIFIER(color_Highlight)
            COMMA(,)
            EXPCHAIN
                IDENTIFIER(color_Inactive)
            COMMA(,)
            EXPCHAIN
                IDENTIFIER(color_Active)
            COMMA(,)
            EXPCHAIN
                IDENTIFIER(color_Highlight)
            COMMA(,)
            EXPCHAIN
                IDENTIFIER(color_Inactive)
            CLOSEBRACKET())
ASSIGNMENT
    EXPCHAIN
        IDENTIFIER(ticks)
    ASSIGN(=)
    NUMBER(0)
NAMEDFUNCTIONDEF
    FUNCTION(function)
    IDENTIFIER(onTick)
    FUNCTIONDEF_PARAMS
        OPENBRACKET(()
        CLOSEBRACKET())
    EXPCHAIN
        IDENTIFIER(LifeBoatAPI)
        DOTACCESS(.)
        IDENTIFIER(LBTouchScreen)
        COLONACCESS(:)
        IDENTIFIER(lbtouchscreen_onTick)
        FUNCTIONCALL
            OPENBRACKET(()
            CLOSEBRACKET())
    ASSIGNMENT
        EXPCHAIN
            IDENTIFIER(ticks)
        ASSIGN(=)
        OPERATORCHAIN
            EXPCHAIN
                IDENTIFIER(ticks)
            BINARY_OP(+)
            NUMBER(1)
    IF_STATEMENT
        IF(if)
        IF_CONDITION
            EXPCHAIN
                IDENTIFIER(myButton)
                COLONACCESS(:)
                IDENTIFIER(lbstyledbutton_isReleased)
                FUNCTIONCALL
                    OPENBRACKET(()
                    CLOSEBRACKET())
        THEN(then)
        ASSIGNMENT
            EXPCHAIN
                IDENTIFIER(isCircleColorToggled)
            ASSIGN(=)
            NOT(not)
            EXPCHAIN
                IDENTIFIER(isCircleColorToggled)
        END(end)
    END(end)
NAMEDFUNCTIONDEF
    FUNCTION(function)
    IDENTIFIER(onDraw)
    FUNCTIONDEF_PARAMS
        OPENBRACKET(()
        CLOSEBRACKET())
    IF_STATEMENT
        IF(if)
        IF_CONDITION
            EXPCHAIN
                IDENTIFIER(isCircleColorToggled)
        THEN(then)
        EXPCHAIN
            IDENTIFIER(color_Active)
            COLONACCESS(:)
            IDENTIFIER(lbcolorrgba_setColor)
            FUNCTIONCALL
                OPENBRACKET(()
                CLOSEBRACKET())
        ELSE(else)
        EXPCHAIN
            IDENTIFIER(color_Inactive)
            COLONACCESS(:)
            IDENTIFIER(lbcolorrgba_setColor)
            FUNCTIONCALL
                OPENBRACKET(()
                CLOSEBRACKET())
        END(end)
    EXPCHAIN
        IDENTIFIER(screen)
        DOTACCESS(.)
        IDENTIFIER(drawCircleF)
        FUNCTIONCALL
            OPENBRACKET(()
            NUMBER(16)
            COMMA(,)
            NUMBER(16)
            COMMA(,)
            OPERATORCHAIN
                PARENTHESIS
                    OPENBRACKET(()
                    OPERATORCHAIN
                        EXPCHAIN
                            IDENTIFIER(ticks)
                        BINARY_OP(%)
                        NUMBER(600)
                    CLOSEBRACKET())
                BINARY_OP(/)
                NUMBER(60)
            CLOSEBRACKET())
    EXPCHAIN
        IDENTIFIER(myButton)
        COLONACCESS(:)
        IDENTIFIER(lbstyledbutton_draw)
        FUNCTIONCALL
            OPENBRACKET(()
            CLOSEBRACKET())
    END(end)
EOF
]]